name: dart_db
description: High-performance embedded key-value database for Dart server applications. LMDB-powered with Rust FFI backend. Perfect for APIs, microservices, and backend systems.
version: 0.2.0
homepage: https://github.com/jhonacodes/dart_db
repository: https://github.com/jhonacodes/dart_db
issue_tracker: https://github.com/jhonacodes/dart_db/issues

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  logger_rs: ^1.0.3
  path: ^1.8.3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6

platforms:
  linux:
  macos:
  windows:

topics:
  - server
  - backend
  - database
  - lmdb
  - api

funding:
  - https://github.com/sponsors/jhonacodes
